[package]
name = "usbloom"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
description = "Explore your USB devices, down to every endpoint"
license = "GPL-3.0-or-later"
repository = "https://github.com/xingrz/usbloom"
publish = false

[dependencies]
anyhow = "1"
cyme = { version = "=3.0.2", default-features = false, features = ["native"] }
gpui-kit = "=0.6.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.dev]
debug = 1

[profile.release]
lto = "thin"
strip = "debuginfo"

[lints.clippy]
dbg_macro = "deny"
todo = "deny"

[patch.crates-io]
cyme = { git = "https://github.com/xingrz/cyme", rev = "4289d2e1f85008431e3ff02cc85474b16533cc72" }
